version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: pdf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: unless-stopped
